export type Disease = {
  id: string;
  name: string;
  crop: string;
  pathogen: string;
  severity: "Low" | "Moderate" | "High";
  symptoms: string[];
  organic: string[];
  chemical: string[];
  prevention: string;
  overview?: string;
  spread?: string;
  conditions?: string;
  parts?: string;
};

export const DISEASES: Disease[] = [
  { id: "tomato-early-blight", name: "Early Blight", crop: "Tomato", pathogen: "Alternaria solani (fungus)", severity: "Moderate",
    symptoms: ["Brown spots with concentric rings", "Yellowing around lesions", "Lower leaves affected first"],
    organic: ["Remove infected lower leaves", "Spray neem oil every 7 days", "Apply Bacillus subtilis bio-fungicide"],
    chemical: ["Chlorothalonil 75% WP @ 2 g/L", "Mancozeb 75% WP @ 2.5 g/L"],
    prevention: "Rotate crops for 2–3 years, mulch soil, water at the base." },
  { id: "tomato-late-blight", name: "Late Blight", crop: "Tomato", pathogen: "Phytophthora infestans (oomycete)", severity: "High",
    symptoms: ["Water-soaked grey-green patches", "White mold under leaves in humidity", "Rapid plant collapse"],
    organic: ["Destroy infected plants immediately", "Copper hydroxide spray (organic-approved)"],
    chemical: ["Metalaxyl + Mancozeb @ 2.5 g/L", "Cymoxanil 8% + Mancozeb 64% @ 3 g/L"],
    prevention: "Use resistant varieties, avoid overhead irrigation, ensure airflow." },
  { id: "potato-late-blight", name: "Late Blight", crop: "Potato", pathogen: "Phytophthora infestans", severity: "High",
    symptoms: ["Dark lesions on leaf tips", "Brown rot on tubers", "Foul smell in fields"],
    organic: ["Hill soil around plants", "Copper-based sprays at first sign"],
    chemical: ["Dimethomorph 50% WP @ 1 g/L", "Mancozeb @ 2.5 g/L preventive"],
    prevention: "Plant certified seed tubers and remove volunteer plants." },
  { id: "rice-blast", name: "Rice Blast", crop: "Rice", pathogen: "Magnaporthe oryzae (fungus)", severity: "High",
    symptoms: ["Diamond-shaped lesions with grey centre", "Neck rot of panicles", "Empty grains"],
    organic: ["Pseudomonas fluorescens seed treatment @ 10 g/kg", "Silica-rich amendments"],
    chemical: ["Tricyclazole 75% WP @ 0.6 g/L", "Isoprothiolane 40% EC @ 1.5 ml/L"],
    prevention: "Avoid excess nitrogen, keep fields flooded evenly." },
  { id: "wheat-rust", name: "Leaf Rust", crop: "Wheat", pathogen: "Puccinia triticina (fungus)", severity: "Moderate",
    symptoms: ["Orange-brown pustules on leaves", "Powdery spores rub off", "Reduced grain fill"],
    organic: ["Sulphur dust @ 25 kg/ha", "Remove volunteer wheat"],
    chemical: ["Propiconazole 25% EC @ 1 ml/L", "Tebuconazole 25.9% EC @ 1 ml/L"],
    prevention: "Grow rust-resistant varieties and sow on time." },
  { id: "corn-leaf-blight", name: "Northern Leaf Blight", crop: "Maize", pathogen: "Exserohilum turcicum", severity: "Moderate",
    symptoms: ["Long cigar-shaped grey lesions", "Lesions merge to blight leaves"],
    organic: ["Trichoderma soil application", "Deep plough crop residue"],
    chemical: ["Azoxystrobin 23% SC @ 1 ml/L", "Mancozeb @ 2.5 g/L"],
    prevention: "Rotate with legumes, choose tolerant hybrids." },
  { id: "grape-powdery", name: "Powdery Mildew", crop: "Grape", pathogen: "Erysiphe necator (fungus)", severity: "Moderate",
    symptoms: ["White powdery coating", "Curled, distorted leaves", "Cracked berries"],
    organic: ["Milk spray (1:9 with water)", "Potassium bicarbonate @ 5 g/L", "Wettable sulphur"],
    chemical: ["Hexaconazole 5% EC @ 1 ml/L", "Myclobutanil 10% WP @ 0.4 g/L"],
    prevention: "Prune for sunlight penetration and airflow." },
  { id: "citrus-canker", name: "Citrus Canker", crop: "Citrus", pathogen: "Xanthomonas citri (bacteria)", severity: "High",
    symptoms: ["Raised corky lesions with yellow halo", "Premature fruit drop"],
    organic: ["Prune and burn infected twigs", "Copper oxychloride (organic grade)"],
    chemical: ["Streptocycline 100 ppm + Copper oxychloride 3 g/L"],
    prevention: "Use windbreaks, disinfect tools, control leaf miners." },
  { id: "banana-sigatoka", name: "Black Sigatoka", crop: "Banana", pathogen: "Pseudocercospora fijiensis (fungus)", severity: "High", overview: "A major leaf-spot disease that cuts photosynthesis and can halve yields.", spread: "Wind-borne and rain-splashed spores", conditions: "Warm (25–28°C), humid, rainy weather", parts: "Leaves",
    symptoms: ["Small reddish-brown streaks on leaves", "Streaks turn black with yellow halo", "Large dead leaf areas", "Premature fruit ripening"],
    organic: ["Cut and remove infected leaves (deleafing)", "Spray neem-based fungicide", "Apply Trichoderma to soil"],
    chemical: ["Propiconazole 25% EC @ 1 ml/L", "Mancozeb 75% WP @ 2.5 g/L"],
    prevention: "Good drainage, wide spacing, remove old leaves regularly." },
  { id: "mango-anthracnose", name: "Anthracnose", crop: "Mango", pathogen: "Colletotrichum gloeosporioides (fungus)", severity: "High", overview: "Damages flowers, young fruit and leaves; causes major post-harvest losses.", spread: "Rain splash and dew", conditions: "Wet, humid weather during flowering", parts: "Leaves, flowers, fruit",
    symptoms: ["Black irregular spots on leaves", "Blossom blight and flower drop", "Sunken black spots on ripe fruit"],
    organic: ["Prune dead twigs and burn", "Hot-water fruit dip (52°C, 5 min)", "Copper oxychloride spray"],
    chemical: ["Carbendazim 50% WP @ 1 g/L", "Azoxystrobin 23% SC @ 1 ml/L"],
    prevention: "Open canopy pruning, spray before flowering in wet seasons." },
  { id: "cotton-leaf-curl", name: "Leaf Curl Virus", crop: "Cotton", pathogen: "Cotton leaf curl virus (Begomovirus)", severity: "High", overview: "A viral disease causing stunting and heavy boll loss.", spread: "Whiteflies (Bemisia tabaci)", conditions: "Hot, dry weather favouring whiteflies", parts: "Leaves, whole plant",
    symptoms: ["Upward or downward leaf curling", "Thickened dark-green veins", "Leaf-like outgrowths under leaves", "Stunted plants"],
    organic: ["Yellow sticky traps", "Neem oil 5 ml/L against whiteflies", "Remove infected plants early"],
    chemical: ["Imidacloprid 17.8% SL @ 0.3 ml/L (for vectors)", "Diafenthiuron 50% WP @ 1.2 g/L"],
    prevention: "Plant tolerant varieties and remove weed hosts." },
  { id: "sugarcane-red-rot", name: "Red Rot", crop: "Sugarcane", pathogen: "Colletotrichum falcatum (fungus)", severity: "High", overview: "Called the 'cancer of sugarcane'; destroys stalks and sugar content.", spread: "Infected setts, water and soil", conditions: "Waterlogging and high humidity", parts: "Stalk, leaves",
    symptoms: ["Yellowing and drying of top leaves", "Red inner stalk with white patches", "Sour alcoholic smell when split"],
    organic: ["Hot-water sett treatment (50°C, 2 h)", "Trichoderma sett dip"],
    chemical: ["Carbendazim 0.1% sett dip for 15 min"],
    prevention: "Use healthy setts, resistant varieties, rotate crops." },
  { id: "groundnut-tikka", name: "Tikka Leaf Spot", crop: "Groundnut", pathogen: "Cercospora arachidicola (fungus)", severity: "Moderate", overview: "Common leaf spot causing early leaf fall and pod loss.", spread: "Wind and rain splash", conditions: "Humid weather, 25–30°C", parts: "Leaves, stems",
    symptoms: ["Circular brown spots with yellow halo", "Dark spots under leaves", "Early leaf drop"],
    organic: ["Neem leaf extract spray 5%", "Remove crop residues"],
    chemical: ["Chlorothalonil 75% WP @ 2 g/L", "Tebuconazole 25.9% EC @ 1 ml/L"],
    prevention: "Crop rotation and timely sowing." },
  { id: "chilli-dieback", name: "Dieback & Fruit Rot", crop: "Chilli", pathogen: "Colletotrichum capsici (fungus)", severity: "High", overview: "Twigs dry from the tip downwards and fruits rot.", spread: "Seed, rain splash", conditions: "Warm, wet weather", parts: "Twigs, fruit",
    symptoms: ["Twigs die back from the tip", "Sunken spots on ripe fruit", "Black dots in lesions"],
    organic: ["Seed treatment with Trichoderma 4 g/kg", "Remove dried twigs"],
    chemical: ["Mancozeb 75% WP @ 2.5 g/L", "Difenoconazole 25% EC @ 0.5 ml/L"],
    prevention: "Use disease-free seed and good field sanitation." },
  { id: "brinjal-wilt", name: "Bacterial Wilt", crop: "Brinjal", pathogen: "Ralstonia solanacearum (bacteria)", severity: "High", overview: "Plants wilt suddenly while leaves are still green.", spread: "Soil, water, tools", conditions: "Hot, moist soil", parts: "Roots, stem",
    symptoms: ["Sudden wilting of green plant", "Brown inner stem", "Milky ooze when stem cut in water"],
    organic: ["Soil application of Pseudomonas fluorescens", "Bleaching powder soil drench 15 kg/ha"],
    chemical: ["Copper oxychloride 3 g/L soil drench"],
    prevention: "Rotate with cereals, grafting on resistant rootstock." },
  { id: "okra-yvmv", name: "Yellow Vein Mosaic", crop: "Okra", pathogen: "Bhendi yellow vein mosaic virus", severity: "High", overview: "Most serious okra disease; fruits become yellow and hard.", spread: "Whiteflies", conditions: "Summer and rainy seasons", parts: "Leaves, fruit",
    symptoms: ["Yellow network of veins", "Whole leaf turns yellow", "Small, pale, tough pods"],
    organic: ["Yellow sticky traps", "Neem seed kernel extract 5%", "Uproot infected plants"],
    chemical: ["Thiamethoxam 25% WG @ 0.3 g/L (for whitefly)"],
    prevention: "Grow resistant varieties and control weeds." },
  { id: "onion-purple-blotch", name: "Purple Blotch", crop: "Onion", pathogen: "Alternaria porri (fungus)", severity: "Moderate", overview: "Leaf disease that reduces bulb size and storage quality.", spread: "Air-borne spores", conditions: "High humidity, 25–30°C", parts: "Leaves, seed stalks",
    symptoms: ["Small white sunken spots", "Purple centre with yellow border", "Leaves collapse"],
    organic: ["Trichoderma spray", "Wider spacing for airflow"],
    chemical: ["Mancozeb 75% WP @ 2.5 g/L", "Tebuconazole @ 1 ml/L"],
    prevention: "Crop rotation and remove debris." },
  { id: "cucumber-downy", name: "Downy Mildew", crop: "Cucumber", pathogen: "Pseudoperonospora cubensis (oomycete)", severity: "High", overview: "Fast-spreading disease that can kill vines within weeks.", spread: "Wind-blown spores", conditions: "Cool nights, wet leaves", parts: "Leaves",
    symptoms: ["Angular yellow patches between veins", "Grey-purple fuzz underneath", "Leaves dry and curl"],
    organic: ["Copper hydroxide spray", "Water early in the day"],
    chemical: ["Metalaxyl + Mancozeb @ 2.5 g/L", "Cymoxanil + Mancozeb @ 3 g/L"],
    prevention: "Resistant varieties, trellising for airflow." },
  { id: "apple-scab", name: "Apple Scab", crop: "Apple", pathogen: "Venturia inaequalis (fungus)", severity: "Moderate", overview: "Causes scabby fruit that cannot be sold fresh.", spread: "Spores from fallen leaves", conditions: "Cool wet spring", parts: "Leaves, fruit",
    symptoms: ["Olive-green velvety spots", "Cracked corky fruit spots", "Early leaf fall"],
    organic: ["Rake and destroy fallen leaves", "Sulphur sprays in spring"],
    chemical: ["Captan 50% WP @ 2 g/L", "Difenoconazole @ 0.3 ml/L"],
    prevention: "Plant scab-resistant varieties, prune for airflow." },
  { id: "strawberry-grey-mold", name: "Grey Mould", crop: "Strawberry", pathogen: "Botrytis cinerea (fungus)", severity: "Moderate", overview: "Rots berries in the field and after picking.", spread: "Air-borne spores", conditions: "Cool, damp, cloudy weather", parts: "Flowers, fruit",
    symptoms: ["Soft brown rot on berries", "Fluffy grey mould growth", "Blighted flowers"],
    organic: ["Straw mulch to keep fruit dry", "Remove rotten fruit daily", "Bacillus subtilis spray"],
    chemical: ["Iprodione 50% WP @ 2 g/L", "Fenhexamid @ 1.5 ml/L"],
    prevention: "Avoid overhead watering, harvest often." },
  { id: "soybean-rust", name: "Soybean Rust", crop: "Soybean", pathogen: "Phakopsora pachyrhizi (fungus)", severity: "High", overview: "Causes rapid defoliation and yield losses up to 80%.", spread: "Wind over long distances", conditions: "Long leaf wetness, 15–28°C", parts: "Leaves",
    symptoms: ["Tan to red-brown tiny lesions", "Raised pustules under leaves", "Early yellowing and leaf drop"],
    organic: ["Early sowing to escape disease", "Sulphur dust"],
    chemical: ["Hexaconazole 5% EC @ 2 ml/L", "Propiconazole @ 1 ml/L"],
    prevention: "Scout often; use tolerant varieties." },
  { id: "papaya-ringspot", name: "Ringspot Virus", crop: "Papaya", pathogen: "Papaya ringspot virus (Potyvirus)", severity: "High", overview: "Can wipe out whole orchards; no cure once infected.", spread: "Aphids", conditions: "All seasons, worse in dry spells", parts: "Leaves, fruit",
    symptoms: ["Mottled yellow leaves", "Dark rings on fruit", "Oily streaks on stems"],
    organic: ["Remove infected trees", "Border crop of maize as barrier"],
    chemical: ["Dimethoate 30% EC @ 1.5 ml/L (aphid control)"],
    prevention: "Use virus-free seedlings, avoid growing near cucurbits." },
  { id: "coffee-rust", name: "Coffee Leaf Rust", crop: "Coffee", pathogen: "Hemileia vastatrix (fungus)", severity: "High", overview: "The most destructive coffee disease worldwide.", spread: "Wind and rain", conditions: "Warm, humid, rainy weather", parts: "Leaves",
    symptoms: ["Yellow-orange powdery spots underneath", "Pale spots on top", "Heavy leaf drop"],
    organic: ["Bordeaux mixture 1%", "Shade management"],
    chemical: ["Hexaconazole 5% EC @ 1 ml/L", "Triadimefon @ 0.5 g/L"],
    prevention: "Resistant varieties, balanced nutrition." },
  { id: "tea-blister", name: "Blister Blight", crop: "Tea", pathogen: "Exobasidium vexans (fungus)", severity: "High", overview: "Attacks tender shoots used for tea, lowering quality.", spread: "Air-borne spores", conditions: "Misty, cool, wet weather", parts: "Young leaves",
    symptoms: ["Pale translucent spots", "Blisters with white velvety underside", "Shoots die"],
    organic: ["Copper oxychloride 0.2%", "Pluck frequently"],
    chemical: ["Hexaconazole @ 1 ml/L", "Propiconazole @ 0.5 ml/L"],
    prevention: "Thin shade trees to reduce humidity." },
  { id: "coconut-bud-rot", name: "Bud Rot", crop: "Coconut", pathogen: "Phytophthora palmivora (oomycete)", severity: "High", overview: "Kills the palm when the growing bud rots.", spread: "Rain, insects", conditions: "Monsoon, high humidity", parts: "Bud, spear leaf",
    symptoms: ["Yellowing of spear leaf", "Spear leaf bends and falls", "Foul-smelling rot at crown"],
    organic: ["Clean rotten tissue and apply Bordeaux paste", "Trichoderma cake at crown"],
    chemical: ["Metalaxyl 2 g/L crown drench"],
    prevention: "Pre-monsoon Bordeaux spray on crown." },
  { id: "pea-powdery", name: "Powdery Mildew", crop: "Pea", pathogen: "Erysiphe pisi (fungus)", severity: "Moderate", overview: "White coating reduces pod set and quality.", spread: "Wind", conditions: "Dry days, cool nights", parts: "Leaves, pods",
    symptoms: ["White powder on leaves and pods", "Leaves turn yellow", "Small, poorly filled pods"],
    organic: ["Wettable sulphur 2 g/L", "Milk spray 1:9"],
    chemical: ["Hexaconazole @ 1 ml/L", "Dinocap @ 1 ml/L"],
    prevention: "Early sowing and resistant varieties." },
  { id: "cabbage-black-rot", name: "Black Rot", crop: "Cabbage", pathogen: "Xanthomonas campestris (bacteria)", severity: "High", overview: "Leaves rot and heads stay small.", spread: "Seed, rain splash, tools", conditions: "Warm, wet weather", parts: "Leaves, veins",
    symptoms: ["V-shaped yellow lesions at leaf edges", "Black veins", "Head rot"],
    organic: ["Hot-water seed treatment (50°C, 30 min)", "Remove infected leaves"],
    chemical: ["Streptocycline 100 ppm + Copper oxychloride 3 g/L"],
    prevention: "Rotate 3 years away from cabbage family." },
  { id: "carrot-leaf-blight", name: "Alternaria Leaf Blight", crop: "Carrot", pathogen: "Alternaria dauci (fungus)", severity: "Moderate", overview: "Weakens tops so roots break during harvest.", spread: "Seed and wind", conditions: "Wet, warm weather", parts: "Leaves",
    symptoms: ["Dark brown spots with yellow edge", "Leaf tips dry", "Tops weaken"],
    organic: ["Use clean seed", "Neem oil spray"],
    chemical: ["Mancozeb @ 2.5 g/L", "Azoxystrobin @ 1 ml/L"],
    prevention: "Crop rotation and drip irrigation." },
  { id: "sunflower-downy", name: "Downy Mildew", crop: "Sunflower", pathogen: "Plasmopara halstedii (oomycete)", severity: "High", overview: "Stunts plants and gives small empty heads.", spread: "Soil and seed", conditions: "Cool, waterlogged soil at sowing", parts: "Whole plant",
    symptoms: ["Stunted plants", "Yellow patches along veins", "White growth under leaves"],
    organic: ["Rotate 4–5 years", "Remove infected seedlings"],
    chemical: ["Metalaxyl seed treatment 6 g/kg"],
    prevention: "Good drainage and resistant hybrids." },
  { id: "mustard-white-rust", name: "White Rust", crop: "Mustard", pathogen: "Albugo candida (oomycete)", severity: "Moderate", overview: "Causes twisted flower stalks called 'stagheads'.", spread: "Wind", conditions: "Cool, foggy weather", parts: "Leaves, flowers",
    symptoms: ["White raised blisters under leaves", "Swollen distorted flowers", "Poor seed set"],
    organic: ["Timely sowing", "Remove stagheads"],
    chemical: ["Metalaxyl + Mancozeb @ 2.5 g/L"],
    prevention: "Crop rotation and clean seed." },
  { id: "chickpea-wilt", name: "Fusarium Wilt", crop: "Chickpea", pathogen: "Fusarium oxysporum f. sp. ciceris", severity: "High", overview: "Soil-borne wilt that can destroy whole fields.", spread: "Soil and seed", conditions: "Warm, dry soil", parts: "Roots, stem",
    symptoms: ["Drooping leaves", "Dark brown inner stem", "Plants dry in patches"],
    organic: ["Trichoderma seed treatment 4 g/kg", "Deep summer ploughing"],
    chemical: ["Carbendazim seed treatment 2 g/kg"],
    prevention: "Wilt-resistant varieties and late sowing." },
  { id: "pomegranate-blight", name: "Bacterial Blight", crop: "Pomegranate", pathogen: "Xanthomonas axonopodis pv. punicae", severity: "High", overview: "Cracks fruit and ruins market value.", spread: "Rain, tools, cuttings", conditions: "Warm, humid monsoon", parts: "Leaves, stems, fruit",
    symptoms: ["Water-soaked leaf spots", "Black oily fruit spots", "Fruit cracking"],
    organic: ["Prune infected parts", "Bordeaux mixture 1%"],
    chemical: ["Streptocycline 0.5 g/L + Copper oxychloride 2.5 g/L"],
    prevention: "Disease-free planting material; disinfect pruning tools." },
  { id: "guava-wilt", name: "Guava Wilt", crop: "Guava", pathogen: "Fusarium oxysporum f. sp. psidii", severity: "High", overview: "Trees yellow and die branch by branch.", spread: "Soil and water", conditions: "Rainy season, alkaline soil", parts: "Roots, branches",
    symptoms: ["Yellowing leaves", "Leaves drop", "Branches dry one by one"],
    organic: ["Aspergillus niger / Trichoderma in pits", "Add lime and organic matter"],
    chemical: ["Carbendazim 0.1% soil drench"],
    prevention: "Avoid waterlogging and injury to roots." },
  { id: "healthy", name: "Healthy Leaf", crop: "Any", pathogen: "None detected", severity: "Low",
    symptoms: ["Uniform green colour", "No lesions or spots"],
    organic: ["Continue compost feeding", "Monitor weekly"],
    chemical: ["No treatment needed"],
    prevention: "Keep balanced nutrition and good field hygiene." },
];
